// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/docs/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/docs/*";
  };
  "pages/landing.tsx": {
    id: "pages/landing";
    page: "/";
  };
  "pages/docs.tsx": {
    id: "pages/docs";
    page: "/docs/*";
  };
};

type RouteModules = {
  "root": typeof import("./src/client/root.tsx");
  "pages/landing": typeof import("./src/client/pages/landing.tsx");
  "pages/docs": typeof import("./src/client/pages/docs.tsx");
};